### PR TITLE
Fixes for new Kilosort 3 pipeline

### PR DESCRIPTION
**Pull request by czuba**
- impose limit to NchanNear for recordings with <100 channels
- GUI: parameterize font size
- GUI: don't crash if default WindowStyle == 'docked'
- Don't reuse figure for datashift plot
- Mmuch faster loading of data for computing whitening matrix
- - Activate by setting ops.useMemMapping = true
- - same method would be great when loading & saving filtered dat,
    but cannot parse method of including overlapping buffers w/in
    filtered data output (can buffer sampling not be done on GPU??)

** svdecon.m was inconsistently performing gpuArray gather,
leading to error attempting to convert "to single from gpuArray"
(Matlab 2019a, Ubuntu 18.04). Added a gather where looked least
intrusive, but just a guess...

### CODE REVIEW

**Comment by marius10p** [comment]
Thanks for all these changes! I am happy to pull in most of them now, except for the progress bar and the memory mapped loading. Happy to still consider those in a separate pull request, but I have to think more about them, because:

1) I think the memory mapping is heavily dependent on OS. Binary file loading is faster for us and we never have to wait for computing the whitening matrix.   
2) The progress bar is nice, but I actually like being able to see how the optimization proceeds for different batches of the data.

**Comment by czuba** [comment]
Not sure how the pull request system works; are you able to selectively merge from a pull request to exclude the get_whitening_matrix changes that you were hesitant about?

I def don't envy the OS compatibility headaches that you have to juggle (multiplied by multiple tools that you et al. support; [praise hands]). The memory mapped loading is something that I grepped a while back from the [spikes repo](https://github.com/cortex-lab/spikes) of your UCL peers. 
Memmapping & parallelized loading amount to a >10x speed improvement (~190 sec to ~12 sec; whitening set to use all data, `ops.nSkipCov=1;`), which is especially significant when tuning/debugging the sorting pipeline for your own data quirks.

**Comment by marius10p** [comment]
If it was doing via multiple pull requests, yes. I could also try to remove it myself, but it would probably take me longer to figure out what I should keep and what not.

**Comment by marius10p** [comment]
I fixed the maximum channels, and the gather problem since those were urgent. It was actually: 

```NchanNearUp =  min(numel(xcup), 10*NchanNear);```

numel(xcup) is the number of "upsampled channels", i.e. template centers. Now the template centers should be determined more smartly for different probe geometries.

**Comment by czuba** [comment]
Wow, that was a mess.  Tried stashing additional changes to roll back & split up commit, disaster ensued. ...props to GitKraken for helping dig out of staging/commit hell.

I moved changes to get_whitening_matrix to a separate file `get_whitening_matrix_faster.m` that can be a drop-in replacement for those interested in trying it.

Looks like there's still some missing parameterization of waveform length in `final_clustering.m` and `ops.sig` usage in `extract_spikes`.

Will put those into a new pull request and close this one.

**Pull request closed without merging**
